name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: arduino/setup-task
        uses: arduino/setup-task@v1.0.3

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: Coverage
        run: task coverage